import 'dart:convert';
import 'dart:io';

import 'src/toolkit_io.dart';

Future<void> main(List<String> args) async {
  final outputPath = _valueAfter(args, '--output') ?? 'assets/diagnostics/build_meta.json';
  final artifactPath = _valueAfter(args, '--artifact');
  final analysisPath = _valueAfter(args, '--analysis');
  final platform = _valueAfter(args, '--platform') ?? 'unmeasured';
  final mode = _valueAfter(args, '--mode') ?? 'release';

  final pubspec = await File('pubspec.yaml').readAsString();
  final versionMatch = RegExp(
    r'^version:\s*([^+\s]+)(?:\+(\d+))?',
    multiLine: true,
  ).firstMatch(pubspec);
  if (versionMatch == null) {
    stderr.writeln('Could not read version from pubspec.yaml');
    exitCode = 2;
    return;
  }

  final screenReport = await _discoverFeatureWeights();
  final routeSourceReport = await _discoverRouteSourceWeights();
  final artifact = artifactPath == null ? null : File(artifactPath);
  final analysis = analysisPath == null ? null : File(analysisPath);
  final report = <String, dynamic>{
    'app': {
      'version': versionMatch.group(1),
      'buildNumber': int.tryParse(versionMatch.group(2) ?? '1') ?? 1,
      'stage': 'pre-beta',
    },
    'measurement': {
      'platform': platform,
      'mode': mode,
      'artifactBytes': artifact != null && await artifact.exists() ? await artifact.length() : null,
      'analysisJsonBytes': analysis != null && await analysis.exists() ? await analysis.length() : null,
      'artifactPath': artifactPath,
      'analysisPath': analysisPath,
      'note': artifactPath == null
          ? 'Source metadata only. Pass --artifact and --analysis after a release/analyze-size build for binary measurements.'
          : 'Artifact measurement snapshot generated by Developer Toolkit.',
    },
    'repository': {
      'sourceBytes': await directorySize(
        Directory.current,
        excludedTopLevel: {'.git', '.dart_tool', 'build'},
      ),
      'assetBytes': await directorySize(Directory('assets')),
    },
    'screens': screenReport,
    'routeSources': routeSourceReport,
  };

  final output = File(outputPath);
  await output.parent.create(recursive: true);
  await output.writeAsString('${const JsonEncoder.withIndent('  ').convert(report)}\n');
  stdout.writeln('Build metadata: ${output.path}');
}

Future<Map<String, dynamic>> _discoverFeatureWeights() async {
  final features = Directory('lib/features');
  if (!await features.exists()) return <String, dynamic>{};

  final directories = <Directory>[];
  await for (final entity in features.list(followLinks: false)) {
    if (entity is! Directory) continue;
    final presentation = Directory(
      '${entity.path}${Platform.pathSeparator}presentation',
    );
    if (await presentation.exists()) directories.add(entity);
  }
  directories.sort((a, b) => a.path.compareTo(b.path));

  final report = <String, dynamic>{};
  for (final feature in directories) {
    final id = feature.uri.pathSegments.where((segment) => segment.isNotEmpty).last;
    final presentation = Directory(
      '${feature.path}${Platform.pathSeparator}presentation',
    );
    report[id] = {
      'sourceBytes': await directorySize(presentation),
      'featureBytes': await directorySize(feature),
    };
  }
  return report;
}

Future<Map<String, dynamic>> _discoverRouteSourceWeights() async {
  final screens = Directory('lib/screens');
  if (!await screens.exists()) return <String, dynamic>{};

  final files = <File>[];
  await for (final entity in screens.list(followLinks: false)) {
    if (entity is File && entity.path.endsWith('.dart')) files.add(entity);
  }
  files.sort((a, b) => a.path.compareTo(b.path));

  final report = <String, dynamic>{};
  for (final file in files) {
    final fileName = file.uri.pathSegments.last;
    final id = fileName.substring(0, fileName.length - '.dart'.length);
    report[id] = {
      'sourceBytes': await file.length(),
      'path': file.path.replaceAll('\\', '/'),
    };
  }
  return report;
}

String? _valueAfter(List<String> args, String flag) {
  final index = args.indexOf(flag);
  if (index < 0 || index + 1 >= args.length) return null;
  final value = args[index + 1].trim();
  return value.isEmpty || value.startsWith('--') ? null : value;
}
