import 'dart:convert';
import 'dart:io';

import 'src/toolkit_io.dart';

Future<void> main(List<String> args) async {
  final outputPath = _valueAfter(args, '--output') ?? 'assets/diagnostics/build_meta.json';
  final artifactPath = _valueAfter(args, '--artifact');
  final analysisPath = _valueAfter(args, '--analysis');
  final platform = _valueAfter(args, '--platform') ?? 'unmeasured';
  final mode = _valueAfter(args, '--mode') ?? 'release';

  final pubspec = await File('pubspec.yaml').readAsString();
  final versionMatch = RegExp(r'^version:\s*([^+\s]+)(?:\+(\d+))?', multiLine: true).firstMatch(pubspec);
  if (versionMatch == null) {
    stderr.writeln('Could not read version from pubspec.yaml');
    exitCode = 2;
    return;
  }

  final screens = <String, String>{
    'home': 'lib/features/home',
    'counter_playground': 'lib/features/counter_playground',
    'irony_generator': 'lib/features/irony_generator',
    'composition_generator': 'lib/features/composition_generator',
    'screen5': 'lib/features/screen5',
  };

  final screenReport = <String, dynamic>{};
  for (final entry in screens.entries) {
    final presentation = Directory('${entry.value}/presentation');
    screenReport[entry.key] = {
      'sourceBytes': await directorySize(presentation),
      'featureBytes': await directorySize(Directory(entry.value)),
    };
  }

  final artifact = artifactPath == null ? null : File(artifactPath);
  final analysis = analysisPath == null ? null : File(analysisPath);
  final report = <String, dynamic>{
    'app': {
      'version': versionMatch.group(1),
      'buildNumber': int.tryParse(versionMatch.group(2) ?? '1') ?? 1,
      'stage': 'pre-beta',
    },
    'measurement': {
      'platform': platform,
      'mode': mode,
      'artifactBytes': artifact != null && await artifact.exists() ? await artifact.length() : null,
      'analysisJsonBytes': analysis != null && await analysis.exists() ? await analysis.length() : null,
      'artifactPath': artifactPath,
      'analysisPath': analysisPath,
      'note': artifactPath == null
          ? 'Source metadata only. Pass --artifact and --analysis after a release/analyze-size build for binary measurements.'
          : 'Artifact measurement snapshot generated by Developer Toolkit.',
    },
    'repository': {
      'sourceBytes': await directorySize(
        Directory.current,
        excludedTopLevel: {'.git', '.dart_tool', 'build'},
      ),
      'assetBytes': await directorySize(Directory('assets')),
    },
    'screens': screenReport,
  };

  final output = File(outputPath);
  await output.parent.create(recursive: true);
  await output.writeAsString('${const JsonEncoder.withIndent('  ').convert(report)}\n');
  stdout.writeln('Build metadata: ${output.path}');
}

String? _valueAfter(List<String> args, String flag) {
  final index = args.indexOf(flag);
  if (index < 0 || index + 1 >= args.length) return null;
  final value = args[index + 1].trim();
  return value.isEmpty || value.startsWith('--') ? null : value;
}
