class NowTimelineStrings {
  const NowTimelineStrings(this.locale);

  final String locale;

  static const supportedLocales = <String>['en', 'ja', 'ar', 'zh', 'fr', 'ru', 'es'];

  static const _values = <String, Map<String, String>>{
    'en': {
      'title': 'Now Timeline',
      'subtitle': 'People, places, schedules and events on one shared timeline.',
      'now': 'Now',
      'people': 'People',
      'places': 'Places',
      'schedules': 'Schedules',
      'events': 'Events',
      'add': 'Add',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'save': 'Save',
      'name': 'Name',
      'timezone': 'IANA timezone',
      'kind': 'Type',
      'start': 'Start',
      'end': 'End',
      'note': 'Note',
      'currentTime': 'Current time',
      'openNow': 'Open now',
      'closedNow': 'Closed now',
      'dst': 'DST',
      'standard': 'Standard time',
      'empty': 'No items yet.',
      'unsupported': 'Stage 1 currently supports Tokyo, London and New York IANA zones.',
      'language': 'Language',
      'person': 'Person',
      'place': 'Place',
      'schedule': 'Schedule',
      'event': 'Event',
    },
    'ja': {
      'title': 'Now Timeline',
      'subtitle': '人・場所・予定・イベントを1本の時間軸にまとめます。',
      'now': '現在',
      'people': '人',
      'places': '場所',
      'schedules': '予定',
      'events': 'イベント',
      'add': '追加',
      'delete': '削除',
      'cancel': 'キャンセル',
      'save': '保存',
      'name': '名前',
      'timezone': 'IANAタイムゾーン',
      'kind': '種類',
      'start': '開始',
      'end': '終了',
      'note': 'メモ',
      'currentTime': '現地時刻',
      'openNow': '営業中',
      'closedNow': '営業時間外',
      'dst': 'サマータイム',
      'standard': '標準時',
      'empty': 'まだ項目がありません。',
      'unsupported': 'Stage 1では東京・ロンドン・ニューヨークのIANAゾーンに対応しています。',
      'language': '言語',
      'person': '人',
      'place': '場所',
      'schedule': '予定',
      'event': 'イベント',
    },
    'ar': {
      'title': 'الخط الزمني الآن',
      'subtitle': 'الأشخاص والأماكن والجداول والأحداث على خط زمني واحد.',
      'now': 'الآن',
      'people': 'الأشخاص',
      'places': 'الأماكن',
      'schedules': 'الجداول',
      'events': 'الأحداث',
      'add': 'إضافة',
      'delete': 'حذف',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'name': 'الاسم',
      'timezone': 'منطقة IANA الزمنية',
      'kind': 'النوع',
      'start': 'البداية',
      'end': 'النهاية',
      'note': 'ملاحظة',
      'currentTime': 'الوقت المحلي',
      'openNow': 'مفتوح الآن',
      'closedNow': 'مغلق الآن',
      'dst': 'التوقيت الصيفي',
      'standard': 'التوقيت القياسي',
      'empty': 'لا توجد عناصر بعد.',
      'unsupported': 'تدعم المرحلة الأولى مناطق طوكيو ولندن ونيويورك.',
      'language': 'اللغة',
      'person': 'شخص',
      'place': 'مكان',
      'schedule': 'جدول',
      'event': 'حدث',
    },
    'zh': {
      'title': 'Now Timeline',
      'subtitle': '把人物、地点、日程和事件放在同一时间线上。',
      'now': '现在', 'people': '人物', 'places': '地点', 'schedules': '日程', 'events': '事件',
      'add': '添加', 'delete': '删除', 'cancel': '取消', 'save': '保存', 'name': '名称',
      'timezone': 'IANA 时区', 'kind': '类型', 'start': '开始', 'end': '结束', 'note': '备注',
      'currentTime': '当地时间', 'openNow': '营业中', 'closedNow': '已关闭', 'dst': '夏令时',
      'standard': '标准时间', 'empty': '暂无项目。', 'unsupported': 'Stage 1 目前支持东京、伦敦和纽约时区。',
      'language': '语言', 'person': '人物', 'place': '地点', 'schedule': '日程', 'event': '事件',
    },
    'fr': {
      'title': 'Now Timeline', 'subtitle': 'Personnes, lieux, horaires et événements sur une même chronologie.',
      'now': 'Maintenant', 'people': 'Personnes', 'places': 'Lieux', 'schedules': 'Horaires', 'events': 'Événements',
      'add': 'Ajouter', 'delete': 'Supprimer', 'cancel': 'Annuler', 'save': 'Enregistrer', 'name': 'Nom',
      'timezone': 'Fuseau IANA', 'kind': 'Type', 'start': 'Début', 'end': 'Fin', 'note': 'Note',
      'currentTime': 'Heure locale', 'openNow': 'Ouvert', 'closedNow': 'Fermé', 'dst': 'Heure d’été',
      'standard': 'Heure standard', 'empty': 'Aucun élément.', 'unsupported': 'Stage 1 prend en charge Tokyo, Londres et New York.',
      'language': 'Langue', 'person': 'Personne', 'place': 'Lieu', 'schedule': 'Horaire', 'event': 'Événement',
    },
    'ru': {
      'title': 'Now Timeline', 'subtitle': 'Люди, места, расписания и события на одной временной шкале.',
      'now': 'Сейчас', 'people': 'Люди', 'places': 'Места', 'schedules': 'Расписания', 'events': 'События',
      'add': 'Добавить', 'delete': 'Удалить', 'cancel': 'Отмена', 'save': 'Сохранить', 'name': 'Название',
      'timezone': 'Часовой пояс IANA', 'kind': 'Тип', 'start': 'Начало', 'end': 'Конец', 'note': 'Заметка',
      'currentTime': 'Местное время', 'openNow': 'Открыто', 'closedNow': 'Закрыто', 'dst': 'Летнее время',
      'standard': 'Стандартное время', 'empty': 'Пока нет элементов.', 'unsupported': 'Stage 1 поддерживает Токио, Лондон и Нью-Йорк.',
      'language': 'Язык', 'person': 'Человек', 'place': 'Место', 'schedule': 'Расписание', 'event': 'Событие',
    },
    'es': {
      'title': 'Now Timeline', 'subtitle': 'Personas, lugares, horarios y eventos en una sola línea temporal.',
      'now': 'Ahora', 'people': 'Personas', 'places': 'Lugares', 'schedules': 'Horarios', 'events': 'Eventos',
      'add': 'Añadir', 'delete': 'Eliminar', 'cancel': 'Cancelar', 'save': 'Guardar', 'name': 'Nombre',
      'timezone': 'Zona horaria IANA', 'kind': 'Tipo', 'start': 'Inicio', 'end': 'Fin', 'note': 'Nota',
      'currentTime': 'Hora local', 'openNow': 'Abierto', 'closedNow': 'Cerrado', 'dst': 'Horario de verano',
      'standard': 'Hora estándar', 'empty': 'Aún no hay elementos.', 'unsupported': 'Stage 1 admite Tokio, Londres y Nueva York.',
      'language': 'Idioma', 'person': 'Persona', 'place': 'Lugar', 'schedule': 'Horario', 'event': 'Evento',
    },
  };

  String text(String key) => _values[locale]?[key] ?? _values['en']![key] ?? key;
  bool get isRtl => locale == 'ar';
}
